// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using car_marketplace_api_3tier.Data;

#nullable disable

namespace car_marketplace_api_3tier.Api.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20250819231154_SeedCars")]
    partial class SeedCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("car_marketplace_api_3tier.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A reliable and fuel-efficient sedan.",
                            ImageUrl = "https://example.com/toyota-corolla.jpg",
                            Location = "Riyadh",
                            Make = "Toyota",
                            Model = "Corolla",
                            Price = 15000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Description = "A sporty compact car with great handling.",
                            ImageUrl = "https://example.com/honda-civic.jpg",
                            Location = "Jeddah",
                            Make = "Honda",
                            Model = "Civic",
                            Price = 14000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            Description = "A classic American muscle car.",
                            ImageUrl = "https://example.com/ford-mustang.jpg",
                            Location = "Dammam",
                            Make = "Ford",
                            Model = "Mustang",
                            Price = 30000m,
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
